---
- name: get os name
  shell: cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2 | tr -d \" | cut -d ' ' -f1
  register: os_name

- name: get os version
  shell: cat /etc/os-release | grep VERSION_ID | cut -d= -f2 | tr -d \" | cut -d ' ' -f1 | cut -d_ -f1
  register: os_version

- name: check
  debug: msg="Найдена ОС {{ os_name.stdout }}, версия {{ os_version.stdout }}"

- name: include OS-specific variables
  include_vars: "{{ os_name.stdout }}-{{ os_version.stdout }}.yml"

- name: Установка требуемых модулей
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ install_packages }}"
  ignore_errors: true

- name: Download
  command: "wget {{ url_download }}"

- name: apt update
  command: apt -y update

- name: apt install
  command: apt -y install zabbix-agent
  ignore_errors: true

- name: change config
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: "^Server="
    line: "Server={{ zabbix_server }}"

- name: restart agent
  service:
    name: zabbix-agent
    state: restarted
